name: GitOps

on:
  push:
    branches:
    - main
jobs:
  sync-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Login to ArgoCD
      uses: clowdhaus/argo-cd-action/@main
      with:
        command: login 34.132.171.46 
        options: --insecure --username admin --password dMQnvoJJrKwZbuHD
    - name: Sync apps
      uses: clowdhaus/argo-cd-action/@main
      with:
        command: argocd app sync go-app
